const truths = [
  "What’s your biggest fear?",
  "What was your very first impression of me?",
  "What’s your ultimate relationship dealbreaker?",
  "Who was the last person you searched on Instagram?",
  "Name something you do only when you’re alone?",
  "What’s your definition of amazing sex?",
  "If you could have sex in any location in the world, where would it be?",
  "If you could have sex with any celebrity, who would it be—and what do you think it would it be like?",
  "What's one of your favorite sexual fantasies?",
  "What do you look like, and sound like, when sex feels good for you?",
  "What's something non-sexual that turns you on?",
  "Do you have a sexual fetish? If so, what is it?",
  "What types of games gave you the most joy as a child?",
 
  "What would an erotic vacation look like for you?",
  "Is there a sexy song that tends to get you in the mood?",
  "Have you ever been caught having sex before?",
  "What's something you've always wanted to ask me to try—but assumed I wouldn't like?",
  "Is there an erotic movie scene that turns you on to watch? Want to watch together?",
  "Where's the wildest place you've ever hooked up with someone before?",
  "Are there types of clothing that you find highly erotic?",
  "Want to try making as much noise during sex as possible?",
  "Want to try sex as quietly as possible, as if we’re trying not to get caught?",
  "Can we spend a night devoted to your pleasure and what makes you feel good?",
  
  "Have you ever fantasized about someone else while having sex?",
  "What color underwear would you like to see me in later?",
  "Do you like playing music in the background or silence?",
  "How many people have you had sex with?",
  "Do you remember the best orgasm you’ve ever had?",
  "Is spanking something you’d like to try with me?",
  "Where would you most like to be kissed?",
  "Which do you like more—sending dirty texts, or dirty talk in person?",
  "Where would you like me to lick you?",
  "What is your favorite position?",
  "How do you feel about anal play?",
  "Have you ever thought about trying tantric sex?",
  
  "What’s your favorite type of foreplay?",
  "What is the most amount of times you've had sex in a single day?",
  "Can you describe the last time you got turned on in public?",
  "Which would you like more—to be in control, or to be dominated?",
  "Would you rather have sex on a plane, or on a moving train?",
  "Have you ever sent or received a nude?",
  "Would you rather have car sex or shower sex?",
  "Do you want us to have a threesome?",
  "What’s the most unusual place you'd like to have sex with me?",
  "Where’s somewhere in our home you'd like to 'christen' with sex?",
  "What's your favorite time of day to have sex?",
  "What is the most embarrassing thing that’s happened during sex?",
  "What’s a secret you’ve never told anyone?",
  
  "What’s your biggest fear?",
  "Do you have a hidden talent?",
  "What’s the worst thing you’ve ever done?",
  "Who’s your least favorite person in this room?",
  "Who would you call to help you bury a body?",
  "What’s one thing you’d never do, even for 1 million dollars?",
 
  "What’s the worst thing you’ve ever said to somebody?",
  "What’s your biggest insecurity?",
  "What’s your most embarrassing childhood memory?",
  "Where’s the weirdest/most adventurous place you’ve had sex?",
  "Do you have any secret fantasies?",
  "What’s your favourite sex position?",
 
  "Name something typically non-sexual that turns you on?",
  "What was your funniest sexual mishap?",
  "Have you ever had a sexy dream about me?",
  "When do you feel your most sensual?",
  "How would you describe the way I taste?",
  "What’s your secret bedroom talent?",
  "What are your top three places to be touched?",
  "Do you prefer to be dominant or submissive?",
  "What sexual act(s) are you not into?",
  "Have you ever had a one-night stand?",
  "Have you ever fantasised about a partner other than me?",
  "What’s the naughtiest thing you’ve ever done in public?",
  "Describe your perfect date night that ends in the bedroom.",
  "Which outfit of mine do you find most irresistible?",
  "Have you ever had a dream about someone else while in a relationship?",
];

const dares = [
  
 
  "Do your best impression of me",
  "Kiss me passionately for five minutes",
  "Give someone a massage, anywhere below the shoulders but above the knees.",
  "Ask someone to describe a sexy dream they’ve had… about you.",
  "Get blindfolded and guess who’s kissing your neck.",
  "Let someone trace their finger along your waistline for 10 seconds.",
  "Act out your go-to move when you’re trying to turn someone on.",
  "Take a shot off someone’s stomach (or inner thigh if they’re into it).",
  "Let someone lick or kiss a body part of your choice… with their permission.",
  "Moan the name of the person you’d most want to hook up with in the room.",
  "Let someone straddle you for 10 seconds, no hands allowed.",
  "Show your favorite “secret” body part, no full nudity necessary.",
  "Dry hump a pillow or couch arm for 15 seconds, eye contact optional.",
  "Let someone give you a hickey (or at least try).",
  "Recreate a scene from a raunchy movie, props allowed.",
  "Switch clothes with someone for the next three rounds.",
  "Ask someone to guide your hand somewhere, wherever they want, for 10 seconds.",
  "Use your tongue to spell out a word on someone’s skin. They have to guess what it is.",
  "Strip down to your underwear and pose like you’re in a magazine shoot.",
  "Let someone sit on your lap and whisper their dirtiest fantasy to you (inaudible to others).",
  "Give someone a “hands only” exploration dare, 30 seconds.",
  "Lick or kiss a body part of your choice… with their permission.",
  "Remove a piece of underwear and hand it to someone in the group.",
  "Simulate oral sex on a banana or popsicle, while maintaining eye contact with someone.",
  "Show the group your favorite nude (yours or someone else’s, with consent).",
  "Let someone take a Polaroid of your “O-face.”",
  "Use a sex toy (or simulate using one) for 30 seconds, clothes on or off, your call.",
  "Let someone of your choice take you to a private corner for 3 minutes, what happens is up to you both.",
  
  "Act out your last hookup scene with someone else playing your partner.",
  "Let everyone in the room vote on a body part they want to see, then reveal it (again, only if you’re 100% comfortable).",
  "Simulate sex positions with a partner of your choice, fully clothed (or not, if you both agree).",
  "With no bottoms, sit on your partner's man piece for 3 mins (women)",
  "With no bottoms, spoon your partner for 5 mins",
  "Give your partner head for 3 minutes",
  "Take an ice cube and run it up and down your partner's body until it is melted",
  "Bite/kiss your partner's booty",
  "Blindfold yourself, Spin around for ten seconds, whoever you are pointing to at the end, go in the next room and enjoy 7 minutes of heaven",
  "Remove your shirt for the rest of the game",
  "Take a naked selfie and send it to your partner",
  "Give your partner's private a peck",
  "Stand inside naked for 3 minutes",
  "Give a hand job for 3 minutes",
  "Make love with your partner for 3 minutes only (must stop after 3 minutes)",
  "Take off your partner's bra (or nearest woman's) using only your teeth",
  "Give a back rub to the person to your right",
  "Wear a pair of your partner's underwear",
  "Put a hickey on the inner thigh of the person to your left",
  "Sensually kiss your challenger for 15 seconds.",
  "Let your challenger do a body shot off of your body.",
  "Beg for permission the next time you need to use the washroom.",
  
  
  "Reproduce all the sounds of a naughty sexy scene in a movie.",
  "Give head to the person next to you for 2 full songs",
  "Make your partner cum using only your hands",
  "Let your partner rub your inner thighs, but don't let yourself get hard",
  "You must act like the sex slave to the person to your right. Doing whatever they say to do for the next 15 minutes.",
  "Go blindfolded and let someone next to you feel your upper body"
];

export { truths, dares };
